# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mailtm < Formula
  desc "CLI client for Mail.tm disposable mail service"
  homepage "https://github.com/ABGEO/mailtm"
  version "0.3.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ABGEO/mailtm/releases/download/v0.3.0/mailtm_0.3.0_Darwin_arm64.tar.gz"
      sha256 "08560855ba98f29a572112a0c6121d1df54b1451ec31dd194f3d91d9d483dd0b"

      def install
        bin.install "mailtm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ABGEO/mailtm/releases/download/v0.3.0/mailtm_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "faea741bac324298b0e5b8d3626a1478090a53cd9ee6a3e95ef0644795ba2fc9"

      def install
        bin.install "mailtm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ABGEO/mailtm/releases/download/v0.3.0/mailtm_0.3.0_Linux_arm64.tar.gz"
      sha256 "5f1f902846eb060573c13920cd1d80e2e4d376d794d77f7330dfd67bab786eeb"

      def install
        bin.install "mailtm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ABGEO/mailtm/releases/download/v0.3.0/mailtm_0.3.0_Linux_x86_64.tar.gz"
      sha256 "25b70d76f3842335f097315349c9e8b14c366861669ba90a34d055b8180359ef"

      def install
        bin.install "mailtm"
      end
    end
  end

  test do
    system "#{bin}/mailtm", "--help"
  end
end
