# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mailtm < Formula
  desc "CLI client for Mail.tm disposable mail service"
  homepage "https://github.com/ABGEO/mailtm"
  version "0.3.1"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ABGEO/mailtm/releases/download/v0.3.1/mailtm_0.3.1_Darwin_x86_64.tar.gz"
      sha256 "989ef27e8796768ecce629c261b6fcc8ad46c61092f4a05ffbb5bcc0be7ff398"

      def install
        bin.install "mailtm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ABGEO/mailtm/releases/download/v0.3.1/mailtm_0.3.1_Darwin_arm64.tar.gz"
      sha256 "e2ec9d75d647c8194e165130b44f34e209828be1764967fd5ad6bcbcf0e8c4d0"

      def install
        bin.install "mailtm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ABGEO/mailtm/releases/download/v0.3.1/mailtm_0.3.1_Linux_arm64.tar.gz"
      sha256 "e0ac053bf3c6e581b97120fa76d3e79bbfd9e27511201877e4ad0d168f92c000"

      def install
        bin.install "mailtm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ABGEO/mailtm/releases/download/v0.3.1/mailtm_0.3.1_Linux_x86_64.tar.gz"
      sha256 "bddad5b6e6aeab6d7dc53f661f38ed1ae5a736bab97a91e01f8a470e10e8bcd7"

      def install
        bin.install "mailtm"
      end
    end
  end

  test do
    system "#{bin}/mailtm", "--help"
  end
end
